name: Rust

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ dep-updated ]
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '*.nix'
      - 'flake.lock'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '*.nix'
      - 'flake.lock'

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 1
  RUSTC_FORCE_INCREMENTAL: 1
  TESTER_PASSWORD: ${{ secrets.TESTER_PASSWORD }}

jobs:
  rust-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update -yy
        sudo apt install -yy --no-install-recommends protobuf-compiler
    - name: Install rust
      run: rustup default 1.53.0 && rustup component add rustfmt clippy

    - name: Cache rust
      uses: Swatinem/rust-cache@v1
    
    - name: Update deps
      run: cargo update --verbose

    - name: Run tests
      run: RUST_LOG=info cargo run --verbose --release --package tests

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore(deps): update rust tests deps"
        branch: main